name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@master
      - name: install all dependencies
        run: |
          sudo apt-get install -y gcc-10
          sudo apt install git gcc mesa-common-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev

      - name: build project template
        run: |
          git clone --recursive https://github.com/MrFrenik/gs_project_template
          cd gs_project_template
          ./proc/linux/gcc.sh
